export type EnglishVocabularyWord = {
  id: string;
  english: string;
  estonian: string;
  category?: string;
  difficulty?: 'easy' | 'medium' | 'hard';
};

export const ENGLISH_VOCABULARY: EnglishVocabularyWord[] = [
  { id: 'word_001', english: 'unit', estonian: 'õppetükk' },
  { id: 'word_002', english: 'Hello.', estonian: 'Tere!' },
  { id: 'word_003', english: 'Hi.', estonian: 'Tere!' },
  { id: 'word_004', english: 'I', estonian: 'mina, ma' },
  { id: 'word_005', english: 'am', estonian: 'olen' },
  { id: 'word_006', english: 'I’m = I am', estonian: 'ma olen' },
  { id: 'word_007', english: 'I’m from', estonian: 'Ma olen pärit' },
  { id: 'word_008', english: 'Britain', estonian: 'Britannia' },
  { id: 'word_009', english: 'America', estonian: 'Ameerika' },
  { id: 'word_010', english: 'Finland', estonian: 'Soome' },
  { id: 'word_011', english: 'Estonia', estonian: 'Eesti' },
  { id: 'word_012', english: 'and', estonian: 'ja, ning' },
  { id: 'word_013', english: 'you', estonian: 'sina, teie' },
  { id: 'word_014', english: 'he', estonian: 'tema (meessoost)' },
  { id: 'word_015', english: 'she', estonian: 'tema (naissoost)' },
  { id: 'word_016', english: 'this', estonian: 'see' },
  { id: 'word_017', english: 'is', estonian: 'on (olema 3. pööre ainsuses)' },
  { id: 'word_018', english: 'He’s / She’s from', estonian: 'Ta on pärit' },
  { id: 'word_019', english: 'good', estonian: 'hea' },
  { id: 'word_020', english: 'morning', estonian: 'hommik' },
  { id: 'word_021', english: 'Good morning!', estonian: 'Tere hommikust!' },
  { id: 'word_022', english: 'Miss', estonian: 'preili' },
  { id: 'word_023', english: 'what', estonian: 'mis (küsisõna)' },
  { id: 'word_024', english: 'what’s = what is', estonian: 'mis on' },
  { id: 'word_025', english: 'your', estonian: 'sinu; teie' },
  { id: 'word_026', english: 'name', estonian: 'nimi' },
  { id: 'word_027', english: 'Sorry.', estonian: 'Vabandust.' },
  { id: 'word_028', english: 'late', estonian: 'hilja' },
  { id: 'word_029', english: 'Sorry, I’m late.', estonian: 'Vabandust, et ma hilinesin.' },
  { id: 'word_030', english: 'that', estonian: 'see (seal)' },
  { id: 'word_031', english: 'that’s = that is', estonian: 'see on' },
  { id: 'word_032', english: 'OK', estonian: 'okei, korras, hästi' },
  { id: 'word_033', english: 'That’s OK.', estonian: 'siin: Sellest pole midagi.' },
  { id: 'word_034', english: 'Goodbye!', estonian: 'Head päeva! Head aega!' },
  { id: 'word_035', english: 'Bye-bye!', estonian: 'Head päeva! Head aega!' },
  { id: 'word_036', english: 'family', estonian: 'perekond' },
  { id: 'word_037', english: 'dad', estonian: 'isa' },
  { id: 'word_038', english: 'my', estonian: 'minu (oma)' },
  { id: 'word_039', english: 'friend', estonian: 'sõber' },
  { id: 'word_040', english: 'Mr', estonian: 'härra' },
  { id: 'word_041', english: 'dog', estonian: 'koer' },
  { id: 'word_042', english: 'mum', estonian: 'ema' },
  { id: 'word_043', english: 'granny', estonian: 'vanaema' },
  { id: 'word_044', english: 'grandad', estonian: 'vanaisa' },
  { id: 'word_045', english: 'brother', estonian: 'vend' },
  { id: 'word_046', english: 'sister', estonian: 'õde' },
  { id: 'word_047', english: 'cat', estonian: 'kass' },
  { id: 'word_048', english: 'his', estonian: 'tema (oma) (meessoost)' },
  { id: 'word_049', english: 'her', estonian: 'tema (oma) (naissoost)' },
  { id: 'word_050', english: 'these', estonian: 'need (siin)' },
  { id: 'word_051', english: 'are', estonian: 'oled, oleme, olete, on (mitmuses)' },
  { id: 'word_052', english: 'big', estonian: 'suur' },
  { id: 'word_053', english: 'small', estonian: 'väike' },
  { id: 'word_054', english: 'girl; girls', estonian: 'tüdruk; tüdrukud' },
  { id: 'word_055', english: 'boy; boys', estonian: 'poiss; poisid' },
  { id: 'word_056', english: 'book', estonian: 'raamat' },
  { id: 'word_057', english: 'ball', estonian: 'pall' },
  { id: 'word_058', english: 'pencil', estonian: 'pliiats' },
  { id: 'word_059', english: 'horse; horses', estonian: 'hobune; hobused' },
  { id: 'word_060', english: 'new', estonian: 'uus' },
  { id: 'word_061', english: 'bike', estonian: 'jalgratas' },
  { id: 'word_062', english: 'cool', estonian: 'äge, vinge' },
  { id: 'word_063', english: 'police', estonian: 'politsei' },
  { id: 'word_064', english: 'in', estonian: 'sees; sisse (eessõna)' },
  { id: 'word_065', english: 'come', estonian: 'tulema' },
  { id: 'word_066', english: 'say', estonian: 'ütlema' },
  { id: 'word_067', english: 'the', estonian: 'artikkel' },
  { id: 'word_068', english: 'the ABC', estonian: 'tähestik' },
  { id: 'word_069', english: 'shoe, shoes', estonian: 'king, kingad' },
  { id: 'word_070', english: 'so', estonian: 'nnii' },
  { id: 'word_071', english: 'beautiful', estonian: 'ilus' },
  { id: 'word_072', english: 'Thanks.', estonian: 'Tänan.' },
  { id: 'word_073', english: 'ladybird', estonian: 'lepatriinu' },
  { id: 'word_074', english: 'tooth; teeth', estonian: 'hammas; hambad' },
  { id: 'word_075', english: 'fairy', estonian: 'haldjas' },
  { id: 'word_076', english: 'tooth fairy', estonian: 'hambahaldjas' },
  { id: 'word_077', english: 'lamb', estonian: '(lamba)tall' },
  { id: 'word_078', english: 'number', estonian: 'number' },
  { id: 'word_079', english: 'one', estonian: 'üks' },
  { id: 'word_080', english: 'two', estonian: 'kaks' },
  { id: 'word_081', english: 'three', estonian: 'kolm' },
  { id: 'word_082', english: 'four', estonian: 'neli' },
  { id: 'word_083', english: 'five', estonian: 'viis' },
  { id: 'word_084', english: 'six', estonian: 'kuus' },
  { id: 'word_085', english: 'tree', estonian: 'puu' },
  { id: 'word_086', english: 'in the tree', estonian: 'puu otsas' },
  { id: 'word_087', english: 'good', estonian: 'hea' },
  { id: 'word_088', english: 'is good at', estonian: 'oskab hästi' },
  { id: 'word_089', english: 'play', estonian: 'mängima' },
  { id: 'word_090', english: 'trick', estonian: 'vemp, vingerpuss' },
  { id: 'word_091', english: 'play tricks', estonian: 'vingerpussi mängima' },
  { id: 'word_092', english: 'playing tricks', estonian: 'vingerpussi mängimine' },
  { id: 'word_093', english: 'it', estonian: 'see' },
  { id: 'word_094', english: 'yes', estonian: 'jah' },
  { id: 'word_095', english: 'Yes, it is.', estonian: 'Jah, see on.' },
  { id: 'word_096', english: 'no', estonian: 'ei' },
  { id: 'word_097', english: 'No, it isn’t.', estonian: 'Ei, see ei ole.' },
  { id: 'word_098', english: 'English', estonian: 'inglise keel' },
  { id: 'word_099', english: 'music', estonian: 'muusika' },
  { id: 'word_100', english: 'sport', estonian: 'sport' },
  { id: 'word_101', english: 'football', estonian: 'jalgpall' },
  { id: 'word_102', english: 'puzzle', estonian: 'mõistatus; pusle' },
  { id: 'word_103', english: 'year', estonian: 'aasta' },
  { id: 'word_104', english: 'I’m in year three.', estonian: 'Ma olen kolmandas klassis.' },
  { id: 'word_105', english: 'a', estonian: 'artikkel' },
  { id: 'word_106', english: 'student', estonian: 'õpilane' },
  { id: 'word_107', english: 'I’m a year-three student.', estonian: 'Ma olen kolmanda klassi õpilane.' },
  { id: 'word_108', english: 'class', estonian: 'klass; tund' },
  { id: 'word_109', english: 'teacher', estonian: 'õpetaja' },
  { id: 'word_110', english: 'class teacher', estonian: 'klassijuhataja' },
  { id: 'word_111', english: 'Mrs', estonian: 'proua' },
  { id: 'word_112', english: 'now', estonian: 'nüüd' },
  { id: 'word_113', english: 'you', estonian: 'sina, sa; teie, te' },
  { id: 'word_114', english: 'see', estonian: 'nägema' },
  { id: 'word_115', english: 'how', estonian: 'kuidas; kui' },
  { id: 'word_116', english: 'well', estonian: 'hästi' },
  { id: 'word_117', english: 'we', estonian: 'meie, me' },
  { id: 'word_118', english: 'know', estonian: 'teadma' },
  { id: 'word_119', english: 'spell', estonian: 'tähthaaval ütlema' },
  { id: 'word_120', english: 'be', estonian: 'olema' },
  { id: 'word_121', english: 'an', estonian: 'artikkel' },
  { id: 'word_122', english: 'school', estonian: 'kool' },
  { id: 'word_123', english: 'think', estonian: 'arvama; mõtlema' },
  { id: 'word_124', english: 'bright', estonian: 'terane, tark' },
  { id: 'word_125', english: 'can', estonian: 'suutma, oskama; võima, tohtima' },
  { id: 'word_126', english: 'read', estonian: 'lugema' },
  { id: 'word_127', english: 'write', estonian: 'kirjutama' },
  { id: 'word_128', english: 'really', estonian: 'tõeliselt, tõepoolest' },
  { id: 'word_129', english: 'they', estonian: 'nemad, nad' },
  { id: 'word_130', english: 'pen', estonian: 'pastapliiats' },
  { id: 'word_131', english: 'pencil case', estonian: 'pinal' },
  { id: 'word_132', english: 'ruler', estonian: 'joonlaud' },
  { id: 'word_133', english: 'rubber', estonian: 'kustukumm' },
  { id: 'word_134', english: 'workbook', estonian: 'töövihik' },
  { id: 'word_135', english: 'diary', estonian: 'õpilaspäevik' },
  { id: 'word_136', english: 'bag', estonian: 'kott' },
  { id: 'word_137', english: 'apple', estonian: 'õun' },
  { id: 'word_138', english: 'seven', estonian: 'seitse' },
  { id: 'word_139', english: 'eight', estonian: 'kaheksa' },
  { id: 'word_140', english: 'nine', estonian: 'üheksa' },
  { id: 'word_141', english: 'ten', estonian: 'kümme' },
  { id: 'word_142', english: 'many', estonian: 'palju' },
  { id: 'word_143', english: 'How many?', estonian: 'Kui palju?' },
  { id: 'word_144', english: 'red', estonian: 'punane' },
  { id: 'word_145', english: 'phone', estonian: 'telefon' },
  { id: 'word_146', english: 'mobile (phone)', estonian: 'mobiil(telefon)' },
  { id: 'word_147', english: 'double', estonian: 'topelt-, kahekordne' },
  { id: 'word_148', english: 'best', estonian: 'parim' },
  { id: 'word_149', english: 'lesson', estonian: 'tund' },
  { id: 'word_150', english: 'room', estonian: 'ruum, tuba' },
  { id: 'word_151', english: 'art', estonian: 'kunst' },
  { id: 'word_152', english: 'oh', estonian: 'oh, oi (hüüdsõna)' },
  { id: 'word_153', english: 'mess', estonian: 'segadus' },
  { id: 'word_154', english: 'What a mess!', estonian: 'Milline segadus!' },
  { id: 'word_155', english: 'help', estonian: 'aitama' },
  { id: 'word_156', english: 'where', estonian: 'kus (küsisõna)' },
  { id: 'word_157', english: 'under', estonian: 'all (eessõna)' },
  { id: 'word_158', english: 'me', estonian: 'mind' },
  { id: 'word_159', english: 'please', estonian: 'palun (midagi küsides)' },
  { id: 'word_160', english: 'of course', estonian: 'muidugi' },
  { id: 'word_161', english: 'thank', estonian: 'tänama' },
  { id: 'word_162', english: 'Thank you.', estonian: 'Tänan sind / teid.' },
  { id: 'word_163', english: 'black', estonian: 'must' },
  { id: 'word_164', english: 'bird', estonian: 'lind' },
  { id: 'word_165', english: 'blackbird', estonian: 'musträstas' },
  { id: 'word_166', english: 'little', estonian: 'väike' },
  { id: 'word_167', english: 'sit', estonian: 'istuma' },
  { id: 'word_168', english: 'on', estonian: 'peal; peale (eessõna)' },
  { id: 'word_169', english: 'hill', estonian: 'küngas' },
  { id: 'word_170', english: 'fly', estonian: 'lendama' },
  { id: 'word_171', english: 'away', estonian: 'ära' },
  { id: 'word_172', english: 'back', estonian: 'tagasi' },
  { id: 'word_173', english: 'white', estonian: 'valge' },
  { id: 'word_174', english: 'wall', estonian: 'müür, sein' },
  { id: 'word_175', english: 'green', estonian: 'roheline' },
  { id: 'word_176', english: 'frog', estonian: 'konn' },
  { id: 'word_177', english: 'pool', estonian: 'lomp; bassein' },
  { id: 'word_178', english: 'jump', estonian: 'hüppama' },
  { id: 'word_179', english: 'long', estonian: 'pikk' },
  { id: 'word_180', english: 'word', estonian: 'sõna' },
  { id: 'word_181', english: 'short', estonian: 'lühike' },
  { id: 'word_182', english: 'verb', estonian: 'tegusõna' },
  { id: 'word_183', english: 'colour', estonian: 'värv' },
  { id: 'word_184', english: 'letter', estonian: 'kirjatäht; kiri' },
  { id: 'word_185', english: 'show', estonian: 'näitama' },
  { id: 'word_186', english: 'start', estonian: 'algus, start; algama; alustama' },
  { id: 'word_187', english: 'finish', estonian: 'lõpp, finiš; lõppema; lõpetama' },
  { id: 'word_188', english: 'battleship', estonian: 'sõjalaev' },
  { id: 'word_189', english: 'play battleships', estonian: 'laevade pommitamist mängima' },
  { id: 'word_190', english: 'hit', estonian: 'tabama, pihta saama' },
  { id: 'word_191', english: 'miss', estonian: 'mitte tabama' },
  { id: 'word_192', english: 'sunk', estonian: 'põhja vajunud, põhjas' },
  { id: 'word_193', english: 'clothes', estonian: 'riided' },
  { id: 'word_194', english: 'yellow', estonian: 'kollane' },
  { id: 'word_195', english: 'pink', estonian: 'roosa' },
  { id: 'word_196', english: 'orange', estonian: 'oranž' },
  { id: 'word_197', english: 'purple', estonian: 'lilla' },
  { id: 'word_198', english: 'brown', estonian: 'pruun' },
  { id: 'word_199', english: 'blue', estonian: 'sinine' },
  { id: 'word_200', english: 'grey', estonian: 'hall (värvus)' },
  { id: 'word_201', english: 'beige', estonian: 'beež' },
  { id: 'word_202', english: 'shirt', estonian: 'särk' },
  { id: 'word_203', english: 'T-shirt', estonian: 'T-särk' },
  { id: 'word_204', english: 'next to', estonian: 'kõrval (eessõna)' },
  { id: 'word_205', english: 'between', estonian: 'vahel (eessõna)' },
  { id: 'word_206', english: 'trousers', estonian: 'püksid' },
  { id: 'word_207', english: 'dress', estonian: 'kleit' },
  { id: 'word_208', english: 'skirt', estonian: 'seelik' },
  { id: 'word_209', english: 'jacket', estonian: 'jakk' },
  { id: 'word_210', english: 'jumper', estonian: 'džemper' },
  { id: 'word_211', english: 'coat', estonian: 'jope' },
  { id: 'word_212', english: 'right', estonian: 'õige' },
  { id: 'word_213', english: 'scarf; scarves', estonian: 'sall; sallid' },
  { id: 'word_214', english: 'too', estonian: 'samuti, ka' },
  { id: 'word_215', english: 'Wow!', estonian: 'Vahva! Tore!' },
  { id: 'word_216', english: 'hat', estonian: 'müts' },
  { id: 'word_217', english: 'present', estonian: 'kingitus' },
  { id: 'word_218', english: 'sweet', estonian: 'armas, kena, kaunis' },
  { id: 'word_219', english: 'favourite', estonian: 'lemmik' },
  { id: 'word_220', english: 'nice', estonian: 'kena, tore' },
  { id: 'word_221', english: 'soft', estonian: 'pehme' },
  { id: 'word_222', english: 'boot', estonian: 'saabas' },
  { id: 'word_223', english: 'sock', estonian: 'sokk' },
  { id: 'word_224', english: 'happy', estonian: 'õnnelik' },
  { id: 'word_225', english: 'birthday', estonian: 'sünnipäev' },
  { id: 'word_226', english: 'Happy birthday!', estonian: 'Palju õnne sünnipäevaks!' },
  { id: 'word_227', english: 'old', estonian: 'vana' },
  { id: 'word_228', english: 'How old … ?', estonian: 'Kui vana …?' },
  { id: 'word_229', english: 'shorts', estonian: 'lühikesed püksid' },
  { id: 'word_230', english: 'top', estonian: 'topp; ülemine osa' },
  { id: 'word_231', english: 'on top of', estonian: 'millegi peal' },
  { id: 'word_232', english: 'other', estonian: 'teine; teised' },
  { id: 'word_233', english: 'box', estonian: 'karp' },
  { id: 'word_234', english: 'table', estonian: 'laud' },
  { id: 'word_235', english: 'chair', estonian: 'tool' },
  { id: 'word_236', english: 'time', estonian: 'aeg' },
  { id: 'word_237', english: 'What’s the time?', estonian: 'Mis kell on?' },
  { id: 'word_238', english: 'What time is it?', estonian: 'Mis kell on?' },
  { id: 'word_239', english: 'clock', estonian: 'kell' },
  { id: 'word_240', english: 'It’s one (o’clock).', estonian: 'Kell on üks.' },
  { id: 'word_241', english: 'excuse', estonian: 'vabandama' },
  { id: 'word_242', english: 'Excuse me!', estonian: 'Vabandust! (pöördumisel)' },
  { id: 'word_243', english: 'eleven', estonian: 'üksteist' },
  { id: 'word_244', english: 'twelve', estonian: 'kaksteist' },
  { id: 'word_245', english: 'almost', estonian: 'peaaegu' },
  { id: 'word_246', english: 'run', estonian: 'jooksma' },
  { id: 'word_247', english: 'Let’s run. = Let us run.', estonian: 'Jookseme! (kaasa kutsumisel)' },
  { id: 'word_248', english: 'dark', estonian: 'pime; tume' },
  { id: 'word_249', english: 'It’s dark.', estonian: 'On pime.' },
  { id: 'word_250', english: 'park', estonian: 'park' },
  { id: 'word_251', english: 'scared', estonian: 'hirmunud' },
  { id: 'word_252', english: 'I’m scared.', estonian: 'Mul on hirm. Ma kardan.' },
  { id: 'word_253', english: 'bus', estonian: 'buss' },
  { id: 'word_254', english: 'take a bus', estonian: 'bussiga minema' },
  { id: 'word_255', english: 'bored', estonian: 'tüdinud' },
  { id: 'word_256', english: 'go', estonian: 'minema' },
  { id: 'word_257', english: 'out', estonian: 'välja, väljas' },
  { id: 'word_258', english: 'look (at)', estonian: '(kedagi / midagi) vaatama' },
  { id: 'word_259', english: 'too', estonian: 'liiga' },
  { id: 'word_260', english: 'then', estonian: 'siis' },
  { id: 'word_261', english: 'Great.', estonian: 'Tore.' },
  { id: 'word_262', english: 'to', estonian: 'sisse, juurde (eessõna)' },
  { id: 'word_263', english: 'to the park', estonian: 'parki' },
  { id: 'word_264', english: 'wrong', estonian: 'vale' },
  { id: 'word_265', english: 'work', estonian: 'töö; töötama' },
  { id: 'word_266', english: 'at', estonian: 'sees, juures (eessõna)' },
  { id: 'word_267', english: 'at work', estonian: 'tööl' },
  { id: 'word_268', english: 'moment', estonian: 'hetk, moment' },
  { id: 'word_269', english: 'at the moment', estonian: 'just praegu' },
  { id: 'word_270', english: 'home', estonian: 'kodu' },
  { id: 'word_271', english: 'at home', estonian: 'kodus' },
  { id: 'word_272', english: 'playschool', estonian: 'lasteaed' },
  { id: 'word_273', english: 'at playschool', estonian: 'lasteaias' },
  { id: 'word_274', english: 'American', estonian: 'ameeriklane' },
  { id: 'word_275', english: 'Estonian', estonian: 'eestlane; eesti keel' },
  { id: 'word_276', english: 'sad', estonian: 'kurb' },
  { id: 'word_277', english: 'tired', estonian: 'väsinud' },
  { id: 'word_278', english: 'upset', estonian: 'endast väljas; ärritunud' },
  { id: 'word_279', english: 'classroom', estonian: 'klass(iruum)' },
  { id: 'word_280', english: 'gym', estonian: 'võimla' },
  { id: 'word_281', english: 'our', estonian: 'meie (oma)' },
  { id: 'word_282', english: 'after', estonian: 'pärast (eessõna)' },
  { id: 'word_283', english: 'sky', estonian: 'taevas' },
  { id: 'word_284', english: 'about', estonian: '(kellegi / millegi) kohta (eessõna)' },
  { id: 'word_285', english: 'What about you?', estonian: 'Kuidas sinuga on?' },
  { id: 'word_286', english: 'swing', estonian: 'kiikuma' },
  { id: 'word_287', english: 'string', estonian: 'nöör' },
  { id: 'word_288', english: 'hum', estonian: 'ümisema' },
  { id: 'word_289', english: 'tune', estonian: 'viis, meloodia' },
  { id: 'word_290', english: 'speak', estonian: 'rääkima' },
  { id: 'word_291', english: 'draw', estonian: 'joonistama' },
  { id: 'word_292', english: 'clown', estonian: 'kloun' },
  { id: 'word_293', english: 'climb', estonian: 'ronima' },
  { id: 'word_294', english: 'climb a tree', estonian: 'puu otsa ronima' },
  { id: 'word_295', english: 'with', estonian: 'koos, -ga (eessõna)' },
  { id: 'word_296', english: 'left', estonian: 'vasak' },
  { id: 'word_297', english: 'hand', estonian: 'käsi' },
  { id: 'word_298', english: 'with your left hand', estonian: 'oma vasaku käega' },
  { id: 'word_299', english: 'skateboard', estonian: 'rula; rulaga sõitma' },
  { id: 'word_300', english: 'do', estonian: 'tegema' },
  { id: 'word_301', english: 'sudoku', estonian: 'sudoku' },
  { id: 'word_302', english: 'do sudokus', estonian: 'sudokusid lahendama' },
  { id: 'word_303', english: 'dance', estonian: 'tantsima' },
  { id: 'word_304', english: 'limbo', estonian: 'limbo (tants, milles liigutakse aina madalamale asetatava lati alt läbi)' },
  { id: 'word_305', english: 'Russian', estonian: 'vene keel' },
  { id: 'word_306', english: 'song', estonian: 'laul' },
  { id: 'word_307', english: 'ride', estonian: 'sõit; sõitma' },
  { id: 'word_308', english: 'ride a horse', estonian: 'ratsutama' },
  { id: 'word_309', english: 'ride a bike', estonian: 'rattaga sõitma' },
  { id: 'word_310', english: 'monster', estonian: 'koletis' },
  { id: 'word_311', english: 'monkey', estonian: 'ahv' },
  { id: 'word_312', english: 'spider', estonian: 'ämblik' },
  { id: 'word_313', english: 'sing', estonian: 'laulma' },
  { id: 'word_314', english: 'swim', estonian: 'ujuma' },
  { id: 'word_315', english: 'free', estonian: 'vaba' },
  { id: 'word_316', english: 'in your free time', estonian: 'vabal ajal' },
  { id: 'word_317', english: 'outside', estonian: 'väljas' },
  { id: 'word_318', english: 'watch', estonian: 'vaatama' },
  { id: 'word_319', english: 'film', estonian: 'film' },
  { id: 'word_320', english: 'game', estonian: 'mäng' },
  { id: 'word_321', english: 'their', estonian: 'nende (oma)' },
  { id: 'word_322', english: 'fantastic', estonian: 'fantastiline, suurepärane' },
  { id: 'word_323', english: 'boring', estonian: 'igav' },
  { id: 'word_324', english: 'day', estonian: 'päev' },
  { id: 'word_325', english: 'find', estonian: 'leidma' },
  { id: 'word_326', english: 'him', estonian: 'teda (meessoost)' },
  { id: 'word_327', english: 'with him', estonian: 'temaga' },
  { id: 'word_328', english: 'guitar', estonian: 'kitarr' },
  { id: 'word_329', english: 'play the guitar', estonian: 'kitarri mängima' },
  { id: 'word_330', english: 'body', estonian: 'keha' },
  { id: 'word_331', english: 'head', estonian: 'pea' },
  { id: 'word_332', english: 'eye', estonian: 'silm' },
  { id: 'word_333', english: 'nose', estonian: 'nina' },
  { id: 'word_334', english: 'neck', estonian: 'kael' },
  { id: 'word_335', english: 'arm', estonian: 'käsivars' },
  { id: 'word_336', english: 'finger', estonian: 'sõrm' },
  { id: 'word_337', english: 'foot; feet', estonian: 'jalg; jalad' },
  { id: 'word_338', english: 'hair', estonian: 'juuksed' },
  { id: 'word_339', english: 'ear', estonian: 'kõrv' },
  { id: 'word_340', english: 'mouth', estonian: 'suu' },
  { id: 'word_341', english: 'shoulder', estonian: 'õlg' },
  { id: 'word_342', english: 'knee', estonian: 'põlv' },
  { id: 'word_343', english: 'leg', estonian: 'jalg; jalasäär' },
  { id: 'word_344', english: 'toe', estonian: 'varvas' },
  { id: 'word_345', english: 'touch', estonian: 'puudutama' },
  { id: 'word_346', english: 'cross', estonian: 'rist; ristama' },
  { id: 'word_347', english: 'Fingers crossed.', estonian: 'Hoiame pöialt.' },
  { id: 'word_348', english: 'Ouch!', estonian: 'Ai!' },
  { id: 'word_349', english: 'hurt', estonian: 'valutama, haiget tegema' },
  { id: 'word_350', english: 'My knee hurts.', estonian: 'Mu põlv valutab.' },
  { id: 'word_351', english: 'Poor you!', estonian: 'Vaeseke!' },
  { id: 'word_352', english: 'get', estonian: 'tooma; saama' },
  { id: 'word_353', english: 'plaster', estonian: 'plaaster' },
  { id: 'word_354', english: 'here', estonian: 'siin' },
  { id: 'word_355', english: 'put on', estonian: 'peale, selga panema' },
  { id: 'word_356', english: 'zebra', estonian: 'sebra' },
  { id: 'word_357', english: 'mouse; mice', estonian: 'hiir; hiired' },
  { id: 'word_358', english: 'giraffe', estonian: 'kaelkirjak' },
  { id: 'word_359', english: 'rabbit', estonian: 'küülik' },
  { id: 'word_360', english: 'squirrel', estonian: 'orav' },
  { id: 'word_361', english: 'have got', estonian: 'omama' },
  { id: 'word_362', english: 'I’ve got = I have got', estonian: 'minul on' },
  { id: 'word_363', english: 'make', estonian: 'tegema' },
  { id: 'word_364', english: 'web', estonian: '(ämbliku)võrk' },
  { id: 'word_365', english: 'tail', estonian: 'saba' },
  { id: 'word_366', english: 'stripe', estonian: 'triip' },
  { id: 'word_367', english: 'spot', estonian: 'laik' },
  { id: 'word_368', english: 'strong', estonian: 'tugev' },
  { id: 'word_369', english: 'but', estonian: 'aga, kuid' },
  { id: 'word_370', english: 'or', estonian: 'või (sidesõna)' },
  { id: 'word_371', english: 'blonde', estonian: 'blond, heledajuukseline' },
  { id: 'word_372', english: 'toy', estonian: 'mänguasi' },
  { id: 'word_373', english: 'train', estonian: 'rong' },
  { id: 'word_374', english: 'set', estonian: 'komplekt' },
  { id: 'word_375', english: 'train set', estonian: 'rongikomplekt' },
  { id: 'word_376', english: 'he’s got = he has got', estonian: 'temal on (meessoost)' },
  { id: 'word_377', english: 'she’s got = she has got', estonian: 'temal on (naissoost)' },
  { id: 'word_378', english: 'doll', estonian: 'nukk' },
  { id: 'word_379', english: 'house', estonian: 'maja' },
  { id: 'word_380', english: 'doll’s house', estonian: 'nukumaja' },
  { id: 'word_381', english: 'pirate', estonian: 'piraat, mereröövel' },
  { id: 'word_382', english: 'ship', estonian: 'laev' },
  { id: 'word_383', english: 'robot', estonian: 'robot' },
  { id: 'word_384', english: 'animal', estonian: 'loom' },
  { id: 'word_385', english: 'mask', estonian: 'mask' },
  { id: 'word_386', english: 'skip', estonian: 'hüppama, hüpetega liikuma' },
  { id: 'word_387', english: 'rope', estonian: 'köis, nöör' },
  { id: 'word_388', english: 'skipping rope', estonian: 'hüppenöör' },
  { id: 'word_389', english: 'model', estonian: 'mudel' },
  { id: 'word_390', english: 'car', estonian: 'auto' },
  { id: 'word_391', english: 'model car', estonian: 'mudelauto' },
  { id: 'word_392', english: 'face', estonian: 'nägu' },
  { id: 'word_393', english: 'paint', estonian: 'värv; värvima' },
  { id: 'word_394', english: 'kite', estonian: 'tuulelohe' },
  { id: 'word_395', english: 'fly a kite', estonian: 'tuulelohe lennutama' },
  { id: 'word_396', english: 'thirteen', estonian: 'kolmteist' },
  { id: 'word_397', english: 'fourteen', estonian: 'neliteist' },
  { id: 'word_398', english: 'fifteen', estonian: 'viisteist' },
  { id: 'word_399', english: 'sixteen', estonian: 'kuusteist' },
  { id: 'word_400', english: 'seventeen', estonian: 'seitseteist' },
  { id: 'word_401', english: 'eighteen', estonian: 'kaheksateist' },
  { id: 'word_402', english: 'nineteen', estonian: 'üheksateist' },
  { id: 'word_403', english: 'twenty', estonian: 'kakskümmend' },
  { id: 'word_404', english: 'man; men', estonian: 'mees; mehed' },
  { id: 'word_405', english: 'both', estonian: 'mõlemad' },
  { id: 'word_406', english: 'like', estonian: 'meeldima' },
  { id: 'word_407', english: 'I like it.', estonian: 'See meeldib mulle.' },
  { id: 'word_408', english: 'crocodile', estonian: 'krokodill' },
  { id: 'word_409', english: 'very', estonian: 'väga' },
  { id: 'word_410', english: 'who', estonian: 'kes (küsisõna)' },
  { id: 'word_411', english: 'sandwich', estonian: 'võileib' },
  { id: 'word_412', english: 'Sunday', estonian: 'pühapäev' },
  { id: 'word_413', english: 'on Sunday', estonian: 'pühapäeval' },
  { id: 'word_414', english: 'Monday', estonian: 'esmaspäev' },
  { id: 'word_415', english: 'Tuesday', estonian: 'teisipäev' },
  { id: 'word_416', english: 'Wednesday', estonian: 'kolmapäev' },
  { id: 'word_417', english: 'Thursday', estonian: 'neljapäev' },
  { id: 'word_418', english: 'Friday', estonian: 'reede' },
  { id: 'word_419', english: 'Saturday', estonian: 'laupäev' },
  { id: 'word_420', english: 'busy', estonian: 'hõivatud, tegevuses' },
  { id: 'word_421', english: 'weekend', estonian: 'nädalavahetus' },
  { id: 'word_422', english: 'at the weekend', estonian: 'nädalavahetusel' },
  { id: 'word_423', english: 'place', estonian: 'koht' },
  { id: 'word_424', english: 'my place', estonian: 'siin: minu kodu' },
  { id: 'word_425', english: 'about', estonian: 'umbes' },
  { id: 'word_426', english: 'At about six.', estonian: 'Umbes kell kuus.' },
  { id: 'word_427', english: 'See you then.', estonian: 'Näeme siis.' },
  { id: 'word_428', english: 'homework', estonian: 'kodutöö' },
  { id: 'word_429', english: 'I’m doing my homework', estonian: 'Ma teen kodutööd.' },
  { id: 'word_430', english: 'eat', estonian: 'sööma' },
  { id: 'word_431', english: 'ice cream', estonian: 'jäätis' },
  { id: 'word_432', english: 'drum', estonian: 'trumm' },
  { id: 'word_433', english: 'play the drums', estonian: 'trummi mängima' },
  { id: 'word_434', english: 'call', estonian: 'helistama; kutsuma; hõikama' },
  { id: 'word_435', english: 'maths', estonian: 'matemaatika' },
  { id: 'word_436', english: 'PE', estonian: 'kehaline kasvatus' },
  { id: 'word_437', english: 'birthday', estonian: 'sünnipäev' },
  { id: 'word_438', english: 'window', estonian: 'aken' },
  { id: 'word_439', english: 'map', estonian: 'maakaart' },
  { id: 'word_440', english: 'door', estonian: 'uks' },
  { id: 'word_441', english: 'photo', estonian: 'foto' },
  { id: 'word_442', english: 'board', estonian: 'tahvel' },
  { id: 'word_443', english: 'desk', estonian: 'koolipink; kirjutuslaud' },
  { id: 'word_444', english: 'card', estonian: '(mängu)kaart; postkaart' },
  { id: 'word_445', english: 'stand', estonian: 'seisma' },
  { id: 'word_446', english: 'talk (to)', estonian: '(kellegagi) rääkima' },
  { id: 'word_447', english: 'take', estonian: 'võtma' },
  { id: 'word_448', english: 'take a photo', estonian: 'pildistama' },
  { id: 'word_449', english: 'sleep', estonian: 'uni; magama' },
  { id: 'word_450', english: 'break', estonian: 'vahetund' },
  { id: 'word_451', english: 'by', estonian: 'juures (eessõna)' },
  { id: 'word_452', english: 'by the window', estonian: 'akna juures' },
  { id: 'word_453', english: 'listen (to)', estonian: '(kedagi / midagi) kuulama' },
  { id: 'word_454', english: 'player', estonian: 'mängija' },
  { id: 'word_455', english: 'another', estonian: 'teine, (keegi või mingi) muu' },
  { id: 'word_456', english: 'camera', estonian: 'fotoaparaat' },
  { id: 'word_457', english: 'palm', estonian: 'palm' },
  { id: 'word_458', english: 'banana', estonian: 'banaan' },
  { id: 'word_459', english: 'e-book', estonian: 'e-raamat' },
  { id: 'word_460', english: 'thing', estonian: 'asi, ese' },
  { id: 'word_461', english: 'study', estonian: 'õppima' },
  { id: 'word_462', english: 'German', estonian: 'saksa keel' },
  { id: 'word_463', english: 'just', estonian: 'just' },
  { id: 'word_464', english: 'just now', estonian: 'just praegu' },
  { id: 'word_465', english: 'Mary speaking.', estonian: 'siin telefonivestluses: Mary kuuleb.' },
  { id: 'word_466', english: 'aunt, auntie', estonian: 'tädi' },
  { id: 'word_467', english: 'How are you?', estonian: 'Kuidas läheb?' },
  { id: 'word_468', english: 'fine', estonian: 'korras, hästi' },
  { id: 'word_469', english: 'I’m fine.', estonian: 'Mul on kõik korras.' },
  { id: 'word_470', english: 'exercise', estonian: 'harjutus' },
  { id: 'word_471', english: 'still', estonian: 'ikka veel' },
  { id: 'word_472', english: 'cook', estonian: 'toitu valmistama' },
  { id: 'word_473', english: 'cartoon', estonian: 'multifilm' },
  { id: 'word_474', english: 'computer', estonian: 'arvuti' },
  { id: 'word_475', english: 'take off', estonian: 'seljast ära võtma' },
  { id: 'word_476', english: 'sofa', estonian: 'diivan' },
  { id: 'word_477', english: 'kitchen', estonian: 'köök' },
  { id: 'word_478', english: 'living room', estonian: 'elutuba' },
  { id: 'word_479', english: 'breakfast', estonian: 'hommikusöök' },
  { id: 'word_480', english: 'make breakfast', estonian: 'hommikusööki valmistama' },
  { id: 'word_481', english: 'eat / have breakfast', estonian: 'hommikusööki sööma' },
  { id: 'word_482', english: 'mend', estonian: 'parandama' },
  { id: 'word_483', english: 'shower', estonian: 'dušš' },
  { id: 'word_484', english: 'have a shower', estonian: 'duši all käima' },
  { id: 'word_485', english: 'child; children', estonian: 'laps; lapsed' },
  { id: 'word_486', english: 'bathroom', estonian: 'vannituba' },
  { id: 'word_487', english: 'toilet', estonian: 'tualett' },
  { id: 'word_488', english: 'garden', estonian: 'aed' },
  { id: 'word_489', english: 'bedroom', estonian: 'magamistuba' },
  { id: 'word_490', english: 'pancake', estonian: 'pannkook' },
  { id: 'word_491', english: 'tidy', estonian: 'korras; korrastama' },
  { id: 'word_492', english: 'wash', estonian: 'pesema' },
  { id: 'word_493', english: 'wash up', estonian: 'nõusid pesema' },
  { id: 'word_494', english: 'cut', estonian: 'lõikama' },
  { id: 'word_495', english: 'watermelon', estonian: 'arbuus' },
  { id: 'word_496', english: 'clean', estonian: 'puhas; puhastama' },
  { id: 'word_497', english: 'turn', estonian: 'pööre; pöörama' },
  { id: 'word_498', english: 'my turn', estonian: 'minu kord (mängus)' },
  { id: 'word_499', english: 'TV', estonian: 'teler, televiisor' },
  { id: 'word_500', english: 'nap', estonian: 'uinak' },
  { id: 'word_501', english: 'have a nap', estonian: 'uinakut tegema' },
  { id: 'word_502', english: 'use', estonian: 'kasutama' },
  { id: 'word_503', english: 'pee', estonian: 'piss; pissima' },
  { id: 'word_504', english: 'have a pee', estonian: 'pissile minema' },
  { id: 'word_505', english: 'around', estonian: 'ümber, ringi' },
  { id: 'word_506', english: 'climb around in the tree', estonian: 'puu otsas ronima' },
  { id: 'word_507', english: 'town', estonian: '(väike)linn, alev' },
  { id: 'word_508', english: 'proud (of)', estonian: 'uhke (kellegi / millegi üle)' },
  { id: 'word_509', english: 'I’m proud (of)', estonian: 'ma olen uhke (kellegi / millegi üle)' },
  { id: 'word_510', english: 'country', estonian: 'maa, riik; maakoht' },
  { id: 'word_511', english: 'flag', estonian: 'lipp' },
  { id: 'word_512', english: 'feel', estonian: 'tundma' },
  { id: 'word_513', english: 'feel good about', estonian: 'kellegi / millegi üle heameelt tundma' },
  { id: 'word_514', english: 'capital (city)', estonian: 'pealinn' },
  { id: 'word_515', english: 'city', estonian: '(suur)linn' },
  { id: 'word_516', english: 'kingdom', estonian: 'kuningriik' },
  { id: 'word_517', english: 'the United Kingdom', estonian: 'Ühendkuningriik' },
  { id: 'word_518', english: 'is called', estonian: 'kutsutakse, nimetatakse' },
  { id: 'word_519', english: 'the Union Flag', estonian: 'Ühendkuningriigi lipp' },
  { id: 'word_520', english: 'river', estonian: 'jõgi' },
  { id: 'word_521', english: 'on the river', estonian: 'jõe kallastel' },
  { id: 'word_522', english: 'live', estonian: 'elama' },
  { id: 'word_523', english: 'I live', estonian: 'ma elan' },
  { id: 'word_524', english: 'the United States (of America)', estonian: 'Ameerika Ühendriigid' },
  { id: 'word_525', english: 'star', estonian: 'täht' },
  { id: 'word_526', english: 'the Stars and Stripes', estonian: '„Tähed ja triibud”; Ameerika Ühendriikide lipp' },
  { id: 'word_527', english: 'president', estonian: 'president' },
  { id: 'word_528', english: 'flat', estonian: 'korter' },
  { id: 'word_529', english: 'cottage', estonian: 'maamaja' },
  { id: 'word_530', english: 'village', estonian: 'küla' },
  { id: 'word_531', english: 'lake', estonian: 'järv' },
  { id: 'word_532', english: 'sea', estonian: 'meri' },
  { id: 'word_533', english: 'far', estonian: 'kaugel' },
  { id: 'word_534', english: 'far from', estonian: 'millestki kaugel' },
  { id: 'word_535', english: 'near', estonian: 'lähedal' },
  { id: 'word_536', english: 'playground', estonian: 'mänguväljak' },
  { id: 'word_537', english: 'in the playground', estonian: 'mänguväljakul' },
  { id: 'word_538', english: 'car park', estonian: 'autoparkla' },
  { id: 'word_539', english: 'supermarket', estonian: 'supermarket' },
  { id: 'word_540', english: 'post office', estonian: 'postkontor' },
  { id: 'word_541', english: 'pool', estonian: 'bassein, ujula' },
  { id: 'word_542', english: 'stop', estonian: 'peatus; peatuma' },
  { id: 'word_543', english: 'bus stop', estonian: 'bussipeatus' },
  { id: 'word_544', english: 'in front of', estonian: 'ees' },
  { id: 'word_545', english: 'behind', estonian: 'taga' },
  { id: 'word_546', english: 'there is / are', estonian: 'lauset sissejuhatav fraas' },
  { id: 'word_547', english: 'when', estonian: 'millal (küsisõna)' },
  { id: 'word_548', english: 'Thames', estonian: 'Thames' },
  { id: 'word_549', english: 'Oxford', estonian: 'Oxford' },
  { id: 'word_550', english: 'Washington D.C.', estonian: 'Washington D.C.' },
  { id: 'word_551', english: 'season', estonian: 'aastaaeg' },
  { id: 'word_552', english: 'January', estonian: 'jaanuar' },
  { id: 'word_553', english: 'February', estonian: 'veebruar' },
  { id: 'word_554', english: 'March', estonian: 'märts' },
  { id: 'word_555', english: 'April', estonian: 'aprill' },
  { id: 'word_556', english: 'May', estonian: 'mai' },
  { id: 'word_557', english: 'June', estonian: 'juuni' },
  { id: 'word_558', english: 'July', estonian: 'juuli' },
  { id: 'word_559', english: 'August', estonian: 'august' },
  { id: 'word_560', english: 'September', estonian: 'september' },
  { id: 'word_561', english: 'October', estonian: 'oktoober' },
  { id: 'word_562', english: 'November', estonian: 'november' },
  { id: 'word_563', english: 'December', estonian: 'detsember' },
  { id: 'word_564', english: 'when', estonian: 'millal (küsisõna)' },
  { id: 'word_565', english: 'holidays', estonian: 'puhkus; koolivaheaeg' },
  { id: 'word_566', english: 'school holidays', estonian: 'koolivaheaeg' },
  { id: 'word_567', english: 'Easter', estonian: 'lihavõtted' },
  { id: 'word_568', english: 'Christmas', estonian: 'jõulud' },
  { id: 'word_569', english: 'Halloween', estonian: 'kõigi pühakute päeva eelõhtu, 31. oktoober' },
  { id: 'word_570', english: 'month', estonian: 'kuu' },
  { id: 'word_571', english: 'spring', estonian: 'kevad' },
  { id: 'word_572', english: 'summer', estonian: 'suvi' },
  { id: 'word_573', english: 'autumn', estonian: 'sügis' },
  { id: 'word_574', english: 'winter', estonian: 'talv' },
  { id: 'word_575', english: 'sunny', estonian: 'päikeseline' },
  { id: 'word_576', english: 'It’s sunny.', estonian: 'On päikeseline.' },
  { id: 'word_577', english: 'windy', estonian: 'tuuline' },
  { id: 'word_578', english: 'hot', estonian: 'kuum, palav' },
  { id: 'word_579', english: 'warm', estonian: 'soe' },
  { id: 'word_580', english: 'rain', estonian: 'vihm; vihma sadama' },
  { id: 'word_581', english: 'It rains in autumn.', estonian: 'Sügisel sajab vihma.' },
  { id: 'word_582', english: 'It’s raining.', estonian: 'Praegu sajab vihma.' },
  { id: 'word_583', english: 'rainy', estonian: 'vihmane' },
  { id: 'word_584', english: 'cold', estonian: 'külm' },
  { id: 'word_585', english: 'snow', estonian: 'lumi; lund sadama' },
  { id: 'word_586', english: 'It snows in winter.', estonian: 'Talvel sajab lund.' },
  { id: 'word_587', english: 'It’s snowing.', estonian: 'Praegu sajab lund.' },
  { id: 'word_588', english: 'beach', estonian: 'supelrand' },
  { id: 'word_589', english: 'snowman', estonian: 'lumememm' },
  { id: 'word_590', english: 'go for a ride', estonian: 'rattaga sõitma minema' },
  { id: 'word_591', english: 'ski', estonian: 'suusk; suusatama' },
  { id: 'word_592', english: 'go skiing', estonian: 'suusatamas käima; suusatama minema' },
  { id: 'word_593', english: 'open', estonian: 'avama' },
  { id: 'word_594', english: 'umbrella', estonian: 'vihmavari' },
  { id: 'word_595', english: 'hug', estonian: 'kallistus; kallistama' },
  { id: 'word_596', english: 'give', estonian: 'andma' },
  { id: 'word_597', english: 'give a hug', estonian: 'kallistama' },
  { id: 'word_598', english: 'sleepy', estonian: 'unine' },
  { id: 'word_599', english: 'sleepy head', estonian: 'unimüts' },
  { id: 'word_600', english: 'mother', estonian: 'ema' },
  { id: 'word_601', english: 'father', estonian: 'isa' },
  { id: 'word_602', english: 'king', estonian: 'kuningas' },
  { id: 'word_603', english: 'water', estonian: 'vesi; kastma' },
  { id: 'word_604', english: 'servant', estonian: 'teener' },
  { id: 'word_605', english: 'So?', estonian: 'Ja siis?' },
  { id: 'word_606', english: 'shopping', estonian: 'ostmine' },
  { id: 'word_607', english: 'go shopping (for food)', estonian: '(toitu) ostmas käima' },
  { id: 'word_608', english: 'food', estonian: 'toit' },
  { id: 'word_609', english: 'chocolate', estonian: 'šokolaad' },
  { id: 'word_610', english: 'orange', estonian: 'apelsin' },
  { id: 'word_611', english: 'yogurt', estonian: 'jogurt' },
  { id: 'word_612', english: 'fruit', estonian: 'puuvili' },
  { id: 'word_613', english: 'salad', estonian: 'salat' },
  { id: 'word_614', english: 'pear', estonian: 'pirn' },
  { id: 'word_615', english: 'for me', estonian: 'mulle, minu jaoks' },
  { id: 'word_616', english: 'much', estonian: 'palju' },
  { id: 'word_617', english: 'How much is it?', estonian: 'Kui palju see maksab?' },
  { id: 'word_618', english: 'cent', estonian: 'sent' },
  { id: 'word_619', english: 'euro', estonian: 'euro' },
  { id: 'word_620', english: 'postcard', estonian: 'postkaart' },
  { id: 'word_621', english: 'buy', estonian: 'ostma' },
  { id: 'word_622', english: 'ticket', estonian: 'pilet' },
  { id: 'word_623', english: 'centre', estonian: 'keskus' },
  { id: 'word_624', english: 'shopping centre', estonian: 'ostukeskus' },
  { id: 'word_625', english: 'only', estonian: 'ainult' },
  { id: 'word_626', english: 'broken', estonian: 'katki' },
  { id: 'word_627', english: 'hungry', estonian: 'näljane' },
  { id: 'word_628', english: 'dirty', estonian: 'määrdunud, must' },
  { id: 'word_629', english: 'in pencil', estonian: 'pliiatsiga' },
  { id: 'word_630', english: 'write in pencil', estonian: 'pliiatsiga kirjutama' },
];

export const ENGLISH_VOCABULARY_COUNT = ENGLISH_VOCABULARY.length;
