export type KirsiReadingPair = {
  id: string;
  word: string;
  image: string;
};

export const KIRSI_READING_PAIRS: KirsiReadingPair[] = [
  { id: 'ema', word: 'EMA', image: '👩' },
  { id: 'isa', word: 'ISA', image: '👨' },
  { id: 'laps', word: 'LAPS', image: '🧒' },
  { id: 'beebi', word: 'BEEBI', image: '👶' },
  { id: 'kasi', word: 'KÄSI', image: '✋' },
  { id: 'jalg', word: 'JALG', image: '🦵' },
  { id: 'suu', word: 'SUU', image: '👄' },
  { id: 'silm', word: 'SILM', image: '👁️' },
  { id: 'nina', word: 'NINA', image: '👃' },
  { id: 'korv', word: 'KÕRV', image: '👂' },
  { id: 'hammas', word: 'HAMMAS', image: '🦷' },
  { id: 'suda', word: 'SÜDA', image: '❤️' },
  { id: 'kass', word: 'KASS', image: '🐱' },
  { id: 'koer', word: 'KOER', image: '🐶' },
  { id: 'siga', word: 'SIGA', image: '🐷' },
  { id: 'lehm', word: 'LEHM', image: '🐮' },
  { id: 'kana', word: 'KANA', image: '🐔' },
  { id: 'kits', word: 'KITS', image: '🐐' },
  { id: 'part', word: 'PART', image: '🦆' },
  { id: 'hiir', word: 'HIIR', image: '🐭' },
  { id: 'karu', word: 'KARU', image: '🐻' },
  { id: 'hunt', word: 'HUNT', image: '🐺' },
  { id: 'janes', word: 'JÄNES', image: '🐰' },
  { id: 'orav', word: 'ORAV', image: '🐿️' },
  { id: 'siil', word: 'SIIL', image: '🦔' },
  { id: 'konn', word: 'KONN', image: '🐸' },
  { id: 'kala', word: 'KALA', image: '🐟' },
  { id: 'lind', word: 'LIND', image: '🐦' },
  { id: 'oun', word: 'ÕUN', image: '🍎' },
  { id: 'pirn', word: 'PIRN', image: '🍐' },
  { id: 'banaan', word: 'BANAAN', image: '🍌' },
  { id: 'kiivi', word: 'KIIVI', image: '🥝' },
  { id: 'sidrun', word: 'SIDRUN', image: '🍋' },
  { id: 'kirss', word: 'KIRSS', image: '🍒' },
  { id: 'arbuus', word: 'ARBUUS', image: '🍉' },
  { id: 'kurk', word: 'KURK', image: '🥒' },
  { id: 'tomat', word: 'TOMAT', image: '🍅' },
  { id: 'kartul', word: 'KARTUL', image: '🥔' },
  { id: 'mais', word: 'MAIS', image: '🌽' },
  { id: 'sibul', word: 'SIBUL', image: '🧅' },
  { id: 'sai', word: 'SAI', image: '🍞' },
  { id: 'leib', word: 'LEIB', image: '🥖' },
  { id: 'juust', word: 'JUUST', image: '🧀' },
  { id: 'muna', word: 'MUNA', image: '🥚' },
  { id: 'piim', word: 'PIIM', image: '🥛' },
  { id: 'vesi', word: 'VESI', image: '💧' },
  { id: 'tort', word: 'TORT', image: '🎂' },
  { id: 'pann', word: 'PANN', image: '🍳' },
  { id: 'pott', word: 'POTT', image: '🍲' },
  { id: 'tass', word: 'TASS', image: '☕' },
  { id: 'kauss', word: 'KAUSS', image: '🥣' },
  { id: 'lusikas', word: 'LUSIKAS', image: '🥄' },
  { id: 'kahvel', word: 'KAHVEL', image: '🍴' },
  { id: 'voodi', word: 'VOODI', image: '🛏️' },
  { id: 'tool', word: 'TOOL', image: '🪑' },
  { id: 'diivan', word: 'DIIVAN', image: '🛋️' },
  { id: 'lamp', word: 'LAMP', image: '💡' },
  { id: 'uks', word: 'UKS', image: '🚪' },
  { id: 'aken', word: 'AKEN', image: '🪟' },
  { id: 'maja', word: 'MAJA', image: '🏠' },
  { id: 'auto', word: 'AUTO', image: '🚗' },
  { id: 'buss', word: 'BUSS', image: '🚌' },
  { id: 'laev', word: 'LAEV', image: '🚢' },
  { id: 'lennuk', word: 'LENNUK', image: '✈️' },
  { id: 'ratas', word: 'RATAS', image: '🚲' },
  { id: 'pall', word: 'PALL', image: '⚽' },
  { id: 'nukk', word: 'NUKK', image: '🪆' },
  { id: 'raamat', word: 'RAAMAT', image: '📖' },
  { id: 'puu', word: 'PUU', image: '🌳' },
  { id: 'lill', word: 'LILL', image: '🌸' }
];
