import { createHash } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { generateKiurMathSession } from '@/lib/exercises/kiurMath';
import { DIFFICULTIES, type Difficulty } from '@/lib/types';

// The maths generator is a replay contract, not just a question factory: the
// server re-generates a session from its stored seed and rejects an uploaded
// attempt whose question text does not match (scoreVerifier.verifyMathQuestion).
// So "same topic + same difficulty + same seed" must keep producing the same
// questions for as long as an offline device may still be holding an attempt.

const SEED = 20260726;
const DIVISION = 'jagamine-kahekohaline-uhekohaline';

function session(difficulty: Difficulty, topic = DIVISION, category = 'Segaharjutus') {
  return generateKiurMathSession(topic, category, difficulty, 15, SEED).map((question) => question.question);
}

function digest(questions: string[]) {
  return createHash('sha256').update(JSON.stringify(questions)).digest('hex').slice(0, 16);
}

describe('generateKiurMathSession determinism', () => {
  it('is stable for the same topic, difficulty and seed', () => {
    expect(session('Lihtne')).toEqual(session('Lihtne'));
  });

  // Change this digest ONLY together with a GENERATOR_VERSION bump in
  // shared/types. A silent change here rejects offline attempts that were
  // generated by an older build and are still waiting to sync.
  it('still produces the questions already-queued attempts were generated from', () => {
    const questions = session('Lihtne');
    expect(questions).toHaveLength(15);
    expect(questions[0]).toBe('Arvuta järgmine jagatis: 22 : 2');
    expect(questions[4]).toBe('Arvuta jagatis: 26 : 2 = ?');
    expect(digest(questions)).toBe('71a4ebaaaaa5dbaf');
  });

  // Difficulty has no picker and every runner sends 'Lihtne', for which
  // divisionQ's branch resolves to the same range an unbranched version would
  // give — so removing it would not change any question the app produces today.
  // It still matters for an outbox attempt minted by an older build that did
  // have the picker, which the server re-generates to verify. This fails the
  // moment the branch is deleted as "unused".
  it('keeps difficulty load-bearing for division', () => {
    expect(DIFFICULTIES).toEqual(['Lihtne', 'Keskmine', 'Raske']);
    const easy = session('Lihtne');
    expect(session('Keskmine')).not.toEqual(easy);
    expect(session('Raske')).not.toEqual(easy);
  });

  // Every other topic ignores difficulty, so the value carried on an attempt
  // cannot change how those are verified.
  it('leaves the other topics unaffected by difficulty', () => {
    for (const topic of ['arvud-10000-piires', 'ring-ja-ringjoon', 'mustrid']) {
      expect(session('Raske', topic)).toEqual(session('Lihtne', topic));
    }
  });
});
